Repository dlang/dub-registry, pull requests merged in 2018-07, with the labels that each got.

#362 Add missing import for std.typecons : tuple
  source/dubregistry/web.d
Labels: auto-merge

#367 Remove inc.package_format.envvars.dt
  views/inc.package_format.envvars.dt
Labels: trivial

#373 Fix #372 - libssl.so.1.0.0 not found in Docker image
  Dockerfile
  README.md
Labels: auto-merge

#375 Remove netlify config files
  netlify.sh
  netlify.toml
Labels: trivial

#371 Update input style
  public/styles/common.css
Labels: auto-merge

#379 Environment fallback for config variables
  app.json
  source/app.d
Labels: auto-merge

#380 Fix import deprecation
  source/dubregistry/registry.d
Labels: auto-merge, trivial
