Repository dlang/dub-registry, pull requests merged in 2018-05, with the labels that each got.

#333 [trivial] Fix a few deprecations
  source/dubregistry/registry.d
  source/dubregistry/web.d
Labels: trivial

#332 Fix #312 - allow to manually configure the documentation url
  source/dubregistry/dbcontroller.d
  source/dubregistry/registry.d
  source/dubregistry/web.d
  views/my_packages.package.dt
  views/view_package.dt
Labels: auto-merge

#337 [trivial] Avoid division by zero when computing the download score.
  source/dubregistry/registry.d
Labels: auto-merge, trivial
