Repository dlang/dub-registry, pull requests merged in 2019-04, with the labels that each got.

#416 Use more than one dummy repositories
  source/app.d
Labels: trivial

#421 Use DMD 2.085.1 for the Heroku previews
  .d-compiler
Labels: trivial

#423 fix broken link
  source/dubregistry/viewutils.d
  views/home.dt
  views/search_results.dt
  views/view_package.dt
Labels: auto-merge

#424 Upgrade to Vibe.d 0.8.5
  dub.sdl
  dub.selections.json
Labels: auto-merge, trivial
